[build]
  command = "echo 'No build command'"
  publish = "frontend/public"

[[redirects]]
  from = "/api/*"
  to = "https://your-python-backend.herokuapp.com/:splat"
  status = 200
  force = true